services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: development
        ports:
            - ${APP_PORT}:${APP_PORT}
        env_file:
            - .env
        depends_on:
            - mysql
            - minio
        volumes:
            - ./:/app

    mysql:
        image: mysql:8.0
        env_file:
            - .env
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: true
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        ports:
            - ${DB_PORT}:${DB_PORT}
        volumes:
            - ./data:/var/lib/mysql

    minio:
        image: minio/minio
        command: server /data --console-address ":9001"
        env_file:
            - .env
        environment:
            MINIO_ROOT_USER: ${S3_USER}
            MINIO_ROOT_PASSWORD: ${S3_PASSWORD}
        ports:
            - ${S3_PORT}:${S3_PORT}
            - '9001:9001'
